---
abstract: 'Build Module::Install based Distributions with Dist::Zilla'
author:
  - 'Kent Fredric <kentnl@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  File::Find: 0
  File::Temp: 0
  Test::More: 0.88
configure_requires:
  ExtUtils::MakeMaker: 6.42
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101900, CPAN::Meta::Converter version 2.101670'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-ModuleInstall
provides:
  Dist::Zilla::Plugin::ModuleInstall:
    file: lib/Dist/Zilla/Plugin/ModuleInstall.pm
    version: 0.01029216
requires:
  Dist::Zilla::File::InMemory: 0
  Dist::Zilla::Role::InstallTool: 0
  Dist::Zilla::Role::PrereqSource: 0
  Dist::Zilla::Role::Tempdir: 0.01027622
  Dist::Zilla::Role::TestRunner: 0
  Dist::Zilla::Role::TextTemplate: 0
  Module::Install: 0.90
  Moose: 0.92
  Moose::Autobox: 0.10
  inc::Module::Install: 0
  namespace::autoclean: 0
resources:
  homepage: http://github.com/kentfredric/Dist-Zilla-Plugin-ModuleInstall/tree
  repository: git://github.com/kentfredric/Dist-Zilla-Plugin-ModuleInstall.git
version: 0.01029216
x_BuiltWith:
  modules:
    Dist::Zilla::File::InMemory: 4.101900
    Dist::Zilla::Role::InstallTool: 4.101900
    Dist::Zilla::Role::PrereqSource: 4.101900
    Dist::Zilla::Role::Tempdir: 0.01027622
    Dist::Zilla::Role::TestRunner: 4.101900
    Dist::Zilla::Role::TextTemplate: 4.101900
    ExtUtils::MakeMaker: 6.56
    File::Find: 1.15
    File::Temp: 0.22
    Module::Install: 1.00
    Moose: 1.08
    Moose::Autobox: 0.11
    Test::More: 0.94
    inc::Module::Install: 1.00
    namespace::autoclean: 0.11
  perl: 5.012001
  platform: linux
  uname: "Linux 2.6.34-gentoo x86_64 GenuineIntel GNU/Linux\n"
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::AutoVersion::Relative
      name: '@KENTNL/AutoVersion::Relative'
      version: 0.01034313
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@KENTNL/GatherDir'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@KENTNL/MetaConfig'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@KENTNL/PruneCruft'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::GithubMeta
      name: '@KENTNL/GithubMeta'
      version: 0.10
    -
      class: Dist::Zilla::Plugin::License
      name: '@KENTNL/License'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@KENTNL/PkgVersion'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@KENTNL/PodWeaver'
      version: 3.101640
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      name: '@KENTNL/MetaProvides::Package'
      version: 1.11034304
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@KENTNL/MetaJSON'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@KENTNL/MetaYAML'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::ReadmeFromPod
      name: '@KENTNL/ReadmeFromPod'
      version: 0.12
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@KENTNL/ManifestSkip'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@KENTNL/Manifest'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::AutoPrereq
      name: '@KENTNL/AutoPrereq'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::MetaData::BuiltWith
      config:
        Dist::Zilla::Plugin::MetaData::BuiltWith:
          _stash_key: x_BuiltWith
          show_uname: 1
          uname:
            uname_args:
              - '-s'
              - '-o'
              - '-r'
              - '-m'
              - '-i'
            uname_call: uname
      name: '@KENTNL/MetaData::BuiltWith'
      version: 0.01005122
    -
      class: Dist::Zilla::Plugin::CompileTests
      name: '@KENTNL/CompileTests'
      version: 1.101800
    -
      class: Dist::Zilla::Plugin::MetaTests
      name: '@KENTNL/MetaTests'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@KENTNL/PodCoverageTests'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@KENTNL/PodSyntaxTests'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::ReportVersions::Tiny
      name: '@KENTNL/ReportVersions::Tiny'
      version: 1.01
    -
      class: Dist::Zilla::Plugin::KwaliteeTests
      name: '@KENTNL/KwaliteeTests'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::PortabilityTests
      name: '@KENTNL/PortabilityTests'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::EOLTests
      name: '@KENTNL/EOLTests'
      version: 0.02
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@KENTNL/ExtraTests'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@KENTNL/TestRelease'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@KENTNL/ConfirmRelease'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@KENTNL/Git::Check'
      version: 1.102040
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@KENTNL/NextRelease'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@KENTNL/Git::Tag/tag_master'
      version: 1.102040
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@KENTNL/Git::Commit'
      version: 1.102040
    -
      class: Dist::Zilla::Plugin::Git::CommitBuild
      name: '@KENTNL/Git::CommitBuild'
      version: 1.102040
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@KENTNL/Git::Tag/tag_release'
      version: 1.102040
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@KENTNL/UploadToCPAN'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::Twitter
      name: '@KENTNL/Twitter'
      version: 0.008
    -
      class: Dist::Zilla::Plugin::ModuleInstall
      name: ModuleInstall
      version: ~
    -
      class: Dist::Zilla::Plugin::Prereq
      config:
        Dist::Zilla::Plugin::Prereqs:
          phase: runtime
          type: requires
      name: Prereq
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.101900
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.101900
